stages:
  - build
  - deploy

before_script:
  - 'dotnet --version'

build_job:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  stage: build  # the build process will only be started by git tag commits
  script:
    - dotnet restore
    - dotnet build --no-restore
    - 'dotnet publish ./ -c Release -o ./bin /clp:ErrorsOnly' 


  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - ./bin

deploy_job:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  dependencies:
    - build_job
  before_script:
    - 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID'
    - 'az account set --subscription $AZURE_SUBSCRIPTION_ID'
  script:
    - 'az webapp deployment --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src-path artifacts.zip'


