image: mcr.microsoft.com/dotnet/sdk:6.0
stages:
  - build
  - deploy

before_script:
  - 'dotnet --version'

build_job:
  stage: build  # the build process will only be started by git tag commits
  script:
    - dotnet restore
    - dotnet build --no-restore
    - 'dotnet publish ./ -c Release -o ./bin /clp:ErrorsOnly' 

  after_script:
    - Invoke-Expression "& '$7z' a .\artifacts\drop.zip .\bin\* '-xr!.exe' '-xr!.pdb' '-xr!*.Development.json'"


  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - ./**/*.zip
