stages:
  - build
  - deploy

before_script:
  - 'dotnet --version'

build_job:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  stage: build  # the build process will only be started by git tag commits
  script:
    - dotnet restore
    - dotnet build --no-restore
    - 'dotnet publish ./ -c Release -o ./bin /clp:ErrorsOnly' 


  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - ./bin

Deploy_stage:
    image: mcr.microsoft.com/azure-cli
    dependencies:
    - build-job
    stage: deploy
    script:
       - # Authenticate with Azure using a service principal
       - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

       - # Set the Azure subscription context
       - az account set --subscription $AZURE_SUBSCRIPTION_ID

       - # Deploy the artifacts to Azure Web App
       - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src artifacts.zip

