stages:
  - build
  - deploy

build_job:
  stage: build  # the build process will only be started by git tag commits
  script:
    - apt-get update
    - apt-get install -y aspnetcore-runtime-6.0
    - dotnet restore
#   artifacts:
#     expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
#     paths:
#       - '$env:EXE_RELEASE_FOLDER\YourApp.exe'  # saving exe to copy to deploy folder
#       - '$env:MSI_RELEASE_FOLDER\YourApp Setup.msi'  # saving msi to copy to deploy folder
#       - '$env:TEST_FOLDER\'  # saving entire Test project so NUnit can run tests
